'use client';

import { useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Atom, Brain, Check, CheckCircle2, ChevronRight, Code2, BookOpen, Menu, X, Sparkles, Target, TrendingUp, Quote, GraduationCap, RotateCcw, Play, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import Brand from '@/components/apex/brand';
import { SAMPLE_QUESTIONS } from '@/lib/mockData';

const Reveal = ({ children, className = '', delay = 0 }) => {
  const reduced = useReducedMotion();
  return <motion.div initial={reduced ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-30px' }} transition={{ duration: 0.55, delay }} className={className}>{children}</motion.div>;
};

const Eyebrow = ({ children, light = false }) => <p className={`text-[11px] font-semibold uppercase tracking-[0.18em] ${light ? 'text-lime' : 'text-primary'}`}>{children}</p>;
const StartButton = ({ onClick, children = 'Start practicing free', className = '' }) => <Button onClick={onClick} className={`h-12 rounded-full px-6 text-sm font-medium shadow-none transition-all hover:-translate-y-0.5 ${className}`}>{children}<ArrowUpRight className="ml-2 h-4 w-4" /></Button>;

const PracticePreview = () => {
  const question = SAMPLE_QUESTIONS['ap-psych'][1];
  const [selected, setSelected] = useState(null);
  const [checked, setChecked] = useState(false);
  const correct = selected === question.correct_answer;
  return (
    <div className="relative mx-auto w-full max-w-[490px]">
      <div aria-hidden="true" className="absolute -inset-x-3 -inset-y-5 rotate-[-5deg] rounded-[32px] bg-lavender sm:-inset-x-5" />
      <div className="relative rounded-2xl border border-border bg-card p-5 shadow-xl shadow-forest/5 sm:p-7">
        <div className="flex items-center justify-between gap-2 border-b border-border pb-4">
          <div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-lavender text-purple-700"><Brain className="h-5 w-5" /></span><div><p className="text-sm font-semibold">AP Psychology</p><p className="mt-0.5 text-[11px] text-muted-foreground">A little practice. A big difference.</p></div></div>
          <span className="rounded-full bg-secondary px-2 py-1 text-[10px] font-medium text-secondary-foreground">TRY IT OUT</span>
        </div>
        <div className="mb-3 mt-5 flex items-center justify-between text-[11px]"><span className="font-medium text-muted-foreground">SAMPLE QUESTION</span><span className="flex items-center gap-1.5 text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Learning</span></div>
        <p className="text-base font-medium leading-relaxed tracking-[-0.3px]">{question.question_text}</p>
        <div className="mt-5 space-y-2" role="group" aria-label="Try a practice question">
          {(question.options || []).map((option) => {
            const active = selected === option.id;
            const isAnswer = checked && option.id === question.correct_answer;
            return <button key={option.id} disabled={checked} aria-pressed={active} onClick={() => setSelected(option.id)} className={`flex w-full items-center gap-3 rounded-lg border px-3 py-2.5 text-left text-[13px] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${isAnswer ? 'border-primary bg-secondary' : checked && active ? 'border-rose-300 bg-rose-50' : active ? 'border-primary bg-secondary' : 'border-border hover:border-primary/50 hover:bg-muted/50'}`}><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-[11px] font-medium ${isAnswer || active ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{isAnswer ? <Check className="h-3.5 w-3.5" /> : option.id}</span>{option.label}</button>;
          })}
        </div>
        <div aria-live="polite">{checked && <div className="mt-4 rounded-lg bg-muted p-3"><p className={`text-xs font-semibold ${correct ? 'text-primary' : 'text-rose-700'}`}>{correct ? 'You got it. Nice work!' : 'Not quite. Let’s break it down.'}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{question.explanation}</p></div>}</div>
        <div className="mt-5 flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><ShieldCheck className="h-3.5 w-3.5" />No sign-up needed</span><Button onClick={() => { if (checked) { setChecked(false); setSelected(null); } else setChecked(true); }} disabled={!selected} className="h-9 rounded-full px-4 text-xs shadow-none">{checked ? <><RotateCcw className="h-3 w-3" />Try again</> : <>Check answer<ArrowRight className="h-3 w-3" /></>}</Button></div>
      </div>
      <div className="absolute -bottom-9 -left-3 flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-lg shadow-forest/5 sm:-left-10">
        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-primary"><TrendingUp className="h-5 w-5" /></div><div><p className="text-[10px] text-muted-foreground">YOUR GOAL. OUR FOCUS.</p><p className="mt-0.5 flex items-center gap-2 text-xl font-semibold">3 <ArrowRight className="h-4 w-4 text-muted-foreground" /><span className="text-primary">5</span><Sparkles className="ml-1 h-4 w-4 text-primary" /></p></div>
      </div>
    </div>
  );
};

const subjects = [
  { id: 'ap-psych', title: 'AP Psychology', category: 'Understand the human mind', icon: Brain, color: 'bg-lavender text-purple-700' },
  { id: 'ap-csp', title: 'AP Computer Science', category: 'Think in possibilities', icon: Code2, color: 'bg-blue-50 text-blue-700' },
  { id: 'ap-physics', title: 'AP Physics', category: 'Make the complex click', icon: Atom, color: 'bg-secondary text-primary' },
  { id: 'honors-precalc', title: 'Honors Precalculus', category: 'Build a stronger foundation', icon: BookOpen, color: 'bg-orange-50 text-orange-700' },
];

const LandingPage = ({ onGetStarted, onSignIn, onChooseSubject }) => {
  const [menuOpen, setMenuOpen] = useState(false);
  const navItems = [['How it works', '#how-it-works'], ['Subjects', '#subjects'], ['About us', '#about'], ['Reviews', '#reviews']];
  const goTo = (event, id) => { event.preventDefault(); setMenuOpen(false); document.querySelector(id)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); };
  return (
    <div id="top" className="min-h-screen overflow-x-clip bg-background text-foreground selection:bg-lime selection:text-forest">
      <div className="flex items-center justify-center gap-2 bg-forest px-4 py-2.5 text-center text-[11px] font-medium text-white sm:text-xs"><Sparkles className="h-3.5 w-3.5 text-lime" /><span>Big goals. Small steps. Your next chapter starts here.</span><button onClick={onGetStarted} className="ml-1 hidden items-center gap-1 text-lime hover:underline sm:inline-flex">Try it free <ArrowRight className="h-3 w-3" /></button></div>
      <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-xl">
        <div className="container flex h-[82px] max-w-[1280px] items-center justify-between gap-4 px-5 sm:px-8">
          <Brand onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} />
          <nav aria-label="Main navigation" className="hidden items-center gap-7 lg:flex">{navItems.map(([label, id]) => <a key={id} href={id} onClick={(e) => goTo(e, id)} className="text-[13px] font-medium text-muted-foreground transition-colors hover:text-primary">{label}</a>)}</nav>
          <div className="flex items-center gap-4"><button onClick={onSignIn} className="hidden text-[13px] font-medium hover:text-primary sm:block">Log in</button><StartButton onClick={onGetStarted} className="h-10 px-5 text-xs">Get started</StartButton><Button aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} aria-controls="mobile-menu" variant="ghost" size="icon" className="lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div>
        </div>
        {menuOpen && <nav id="mobile-menu" aria-label="Mobile navigation" className="border-t border-border bg-background px-6 py-4 lg:hidden">{navItems.map(([label, id]) => <a key={id} href={id} onClick={(e) => goTo(e, id)} className="block rounded-md py-3 text-sm font-medium hover:text-primary">{label}</a>)}<button onClick={onSignIn} className="py-3 text-sm font-semibold text-primary">Log in</button></nav>}
      </header>
      <main>
        <section className="container grid max-w-[1280px] items-center gap-16 px-6 pb-24 pt-14 sm:px-8 sm:pt-20 lg:min-h-[660px] lg:grid-cols-[1.08fr_1fr] lg:gap-20 lg:pb-24 lg:pt-16">
          <Reveal>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-secondary/60 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />A smarter way to AP</div>
            <h1 className="max-w-xl text-[48px] font-medium leading-[1.06] tracking-[-2.8px] sm:text-[64px] sm:tracking-[-3.5px] xl:text-[72px]">Big AP goals.<br />Meet your<br /><span className="relative inline-block text-primary">game plan.<span aria-hidden="true" className="absolute -bottom-2 left-0 h-2 w-full -rotate-1 rounded-full bg-lime/75" /></span></h1>
            <p className="mt-8 max-w-[420px] text-base leading-[1.75] text-muted-foreground">Aiming to go from a <strong className="font-semibold text-foreground">3 to a 5?</strong> Turn “where do I start?” into “I’ve got this” with AP-style practice, clear explanations, and one focused step at a time.</p>
            <div className="mt-7 flex flex-wrap items-center gap-5"><StartButton onClick={onGetStarted} /><a href="#how-it-works" onClick={(e) => goTo(e, '#how-it-works')} className="inline-flex items-center gap-2 text-[13px] font-medium hover:text-primary"><span className="flex h-8 w-8 items-center justify-center rounded-full border border-border"><Play className="ml-0.5 h-3 w-3 fill-current" /></span>See how it works</a></div>
            <div className="mt-5 flex flex-wrap items-center gap-4 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-primary" />Free to get started</span><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-primary" />No credit card needed</span></div>
          </Reveal>
          <Reveal delay={0.15} className="px-2 pb-6 sm:px-5 lg:pb-0"><PracticePreview /></Reveal>
        </section>
        <section className="border-y border-border bg-card/70">
          <div className="container grid max-w-[1280px] grid-cols-2 gap-6 px-6 py-7 sm:px-8 lg:grid-cols-[1.25fr_1fr_1fr_1fr] lg:gap-8">
            <p className="text-xs leading-relaxed text-muted-foreground">Less guesswork.<br /><span className="font-semibold text-foreground">More “I’m ready for this.”</span></p>
            {[{ icon: Target, label: 'Focused practice' }, { icon: CheckCircle2, label: 'Clear explanations' }, { icon: TrendingUp, label: 'Progress you can see' }].map(({ icon: Icon, label }) => <div key={label} className="flex items-center gap-3"><Icon className="h-5 w-5 text-primary" strokeWidth={1.5} /><span className="text-xs font-medium sm:text-sm">{label}</span></div>)}
          </div>
        </section>
        <section id="how-it-works" className="container max-w-[1280px] scroll-mt-28 px-6 py-24 sm:px-8">
          <Reveal className="text-center"><Eyebrow>Small steps. Big ambitions.</Eyebrow><h2 className="mt-4 text-3xl font-medium tracking-[-1.5px] sm:text-[44px] sm:leading-[1.15]">Your path from <span className="text-primary">3 → 5.</span></h2><p className="mx-auto mt-4 max-w-lg text-sm leading-relaxed text-muted-foreground">You don’t need to study everything at once.<br className="hidden sm:block" /> You need to know what to practice next.</p></Reveal>
          <div className="mt-12 grid gap-5 md:grid-cols-3">
            <Reveal className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex h-48 items-end justify-center bg-lavender/70 px-9 pt-8"><div className="w-full max-w-[250px] rounded-t-xl border border-border bg-card p-5 pb-7"><p className="text-[10px] text-muted-foreground">YOUR STARTING POINT</p><div className="mt-3 flex items-baseline gap-2"><span className="text-3xl font-medium tracking-tight">Let’s find it.</span><Target className="h-5 w-5 text-purple-500" /></div><div className="mt-4 space-y-2"><div className="h-2 w-4/5 rounded-full bg-purple-200" /><div className="h-2 w-3/5 rounded-full bg-purple-100" /><div className="h-2 w-11/12 rounded-full bg-purple-100" /></div></div></div><div className="p-7"><span className="text-xs font-medium text-muted-foreground">01 / FIND YOUR FOCUS</span><h3 className="mt-3 text-xl font-medium tracking-tight">Start where you are.</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Pick your subjects and try a practice session. Find out what clicks—and what needs a little more work.</p></div></Reveal>
            <Reveal delay={0.08} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex h-48 items-center justify-center bg-secondary px-9"><div className="w-full max-w-[250px] rounded-xl border border-border bg-card p-4 shadow-sm"><p className="mb-3 text-xs font-semibold">A little progress, every day.</p>{['Practice a tricky concept', 'Understand the explanation', 'Try it again with confidence'].map((item, i) => <div key={item} className="flex items-center gap-2 border-t border-border py-2 text-[10px]"><span className={`flex h-4 w-4 items-center justify-center rounded-full ${i < 2 ? 'bg-primary text-white' : 'border border-border'}`}>{i < 2 && <Check className="h-3 w-3" />}</span>{item}</div>)}</div></div><div className="p-7"><span className="text-xs font-medium text-muted-foreground">02 / MAKE IT CLICK</span><h3 className="mt-3 text-xl font-medium tracking-tight">Practice with purpose.</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Work through bite-sized drills with instant feedback. Learn the why behind an answer, not just the letter.</p></div></Reveal>
            <Reveal delay={0.16} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex h-48 items-end justify-center gap-3 bg-peach px-12 pb-6"><div className="flex h-16 w-14 items-end justify-center rounded-t-lg bg-orange-200 pb-2 text-xl font-medium text-orange-800">3</div><div className="flex h-24 w-14 items-end justify-center rounded-t-lg bg-orange-300 pb-2 text-xl font-medium text-orange-900">4</div><div className="relative flex h-32 w-14 items-end justify-center rounded-t-lg bg-primary pb-2 text-xl font-medium text-white"><Sparkles className="absolute top-3 h-5 w-5 text-lime" />5</div></div><div className="p-7"><span className="text-xs font-medium text-muted-foreground">03 / AIM HIGHER</span><h3 className="mt-3 text-xl font-medium tracking-tight">Build your confidence.</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Bring it all together in a practice test. Review your results, keep improving, and walk in with a plan.</p></div></Reveal>
          </div>
          <p className="mt-5 text-center text-[11px] text-muted-foreground">Your score is your goal, not a guarantee. Results depend on preparation and exam-day performance.</p>
        </section>
        <section className="bg-forest text-white">
          <div className="container grid max-w-[1280px] items-center gap-12 px-6 py-20 sm:px-8 lg:grid-cols-2 lg:gap-24">
            <Reveal><Eyebrow light>Practice that has a purpose</Eyebrow><h2 className="mt-5 text-3xl font-medium leading-tight tracking-[-1.5px] sm:text-[44px]">Less unfamiliar.<br />More <span className="text-lime">“I’ve seen this.”</span></h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Get comfortable with AP-style questions before the pressure is on. Practice the concepts, understand the reasoning, and build the habits that help on test day.</p><div className="mt-7 space-y-4">{['Multiple-choice practice across key concepts', 'Explanations that go beyond right or wrong', 'A focused space to work, review, and repeat'].map(text => <div key={text} className="flex items-center gap-3 text-sm text-white/90"><CheckCircle2 className="h-4 w-4 text-lime" />{text}</div>)}</div><StartButton onClick={onGetStarted} className="mt-8 bg-lime text-forest hover:bg-lime/90">Explore the practice demo</StartButton><p className="mt-4 max-w-md text-[10px] leading-relaxed text-white/50">Current demo uses sample questions and simulated tests. Content has not yet been validated against official AP exams.</p></Reveal>
            <Reveal className="rounded-2xl border border-white/15 bg-white/5 p-6 sm:p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full bg-lime" />THE APEX APPROACH</div><BookOpen className="h-5 w-5 text-white/50" /></div><div className="my-8 space-y-3">{[{ label: 'Try a question', detail: 'Put what you know into practice', icon: Target }, { label: 'Understand the answer', detail: 'Connect the concept, not just the dots', icon: Brain }, { label: 'Take the next step', detail: 'Turn small wins into a study habit', icon: TrendingUp }].map(({ label, detail, icon: Icon }, index) => <div key={label} className="flex items-center gap-4 rounded-xl bg-white/[0.07] p-4"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${index === 1 ? 'bg-lavender text-forest' : 'bg-lime/10 text-lime'}`}><Icon className="h-5 w-5" /></span><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-[11px] text-white/60">{detail}</p></div><ChevronRight className="ml-auto h-4 w-4 shrink-0 text-white/40" /></div>)}</div><div className="border-t border-white/15 pt-5 text-center text-xs text-white/60">Not more hours. <span className="text-lime">More meaningful practice.</span></div></Reveal>
          </div>
        </section>
        <section id="subjects" className="container max-w-[1280px] scroll-mt-28 px-6 py-24 sm:px-8"><Reveal className="flex flex-wrap items-end justify-between gap-5"><div><Eyebrow>Find your focus</Eyebrow><h2 className="mt-4 text-3xl font-medium tracking-[-1.5px] sm:text-[42px]">Your subjects. One study space.</h2></div><p className="max-w-xs text-sm leading-relaxed text-muted-foreground">Choose a subject and take your first step.<br />More courses are on the way.</p></Reveal><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{subjects.map(({ id, title, category, icon: Icon, color }, index) => <Reveal key={id} delay={index * 0.05}><button onClick={() => onChooseSubject(id)} className="group h-full w-full rounded-2xl border border-border bg-card p-6 text-left transition-all hover:-translate-y-1 hover:border-primary/35 hover:shadow-lg hover:shadow-forest/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-base font-semibold tracking-tight">{title}</h3><p className="mt-2 text-xs text-muted-foreground">{category}</p><div className="mt-7 flex items-center justify-between text-xs font-medium text-primary">Explore subject<ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div></button></Reveal>)}</div></section>
        <section id="about" className="scroll-mt-20 border-y border-border bg-secondary/40"><div className="container grid max-w-[1280px] gap-12 px-6 py-20 sm:px-8 md:grid-cols-2 md:gap-20"><Reveal><Eyebrow>About ApexPrep</Eyebrow><h2 className="mt-5 text-3xl font-medium leading-tight tracking-[-1.5px] sm:text-[44px]">A big score starts<br />with believing<br /><span className="text-primary">you can get there.</span></h2></Reveal><Reveal className="flex flex-col justify-center"><p className="text-lg font-medium leading-relaxed tracking-tight">AP prep should open doors.<br />Not leave you feeling overwhelmed.</p><p className="mt-5 text-sm leading-7 text-muted-foreground">That’s the idea behind ApexPrep: a calmer, clearer way to turn big goals into everyday progress. We bring practice, explanations, and your study journey into one focused space.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">Whether you’re building your foundation or aiming for a 5, start with what you know. We’ll give you a place to practice what comes next.</p><div className="mt-6 flex items-center gap-3 text-xs font-medium text-primary"><GraduationCap className="h-5 w-5" />Built around the way students learn.</div></Reveal></div></section>
        <section id="reviews" className="container max-w-[1280px] scroll-mt-28 px-6 py-24 sm:px-8"><Reveal className="text-center"><Eyebrow>Student perspectives</Eyebrow><h2 className="mt-4 text-3xl font-medium tracking-[-1.5px] sm:text-[42px]">Less stress. More “I get it.”</h2><p className="mt-4 text-sm text-muted-foreground">A preview of the experience we’re building for students.</p><span className="mt-4 inline-block rounded-full border border-border bg-muted px-3 py-1 text-[10px] text-muted-foreground">Illustrative reviews · not verified student testimonials</span></Reveal><div className="mt-10 grid gap-5 md:grid-cols-3">{[{ title: 'A clearer place to start.', quote: 'Instead of staring at a whole textbook, I can pick a subject and work through one question at a time.', subject: 'AP Psychology', color: 'bg-lavender' }, { title: 'The “why” makes it click.', quote: 'Seeing the explanation after each answer helps me understand the idea instead of just memorizing a letter.', subject: 'AP Computer Science', color: 'bg-secondary' }, { title: 'Small steps feel doable.', quote: 'Short practice sessions make it easier to get started. I like having my subjects together in one place.', subject: 'AP Physics', color: 'bg-peach' }].map(({ title, quote, subject, color }, i) => <Reveal key={title} delay={i * 0.06} className="flex flex-col rounded-2xl border border-border bg-card p-7"><Quote className="h-7 w-7 text-primary/40" /><h3 className="mt-5 text-lg font-medium tracking-tight">{title}</h3><blockquote className="mb-7 mt-3 flex-1 text-sm leading-7 text-muted-foreground">“{quote}”</blockquote><div className="flex items-center gap-3 border-t border-border pt-5"><div className={`flex h-9 w-9 items-center justify-center rounded-full ${color}`}><GraduationCap className="h-4 w-4" /></div><div><p className="text-xs font-medium">Sample student perspective</p><p className="mt-0.5 text-[11px] text-muted-foreground">{subject} · Illustrative review</p></div></div></Reveal>)}</div></section>
        <section id="faq" className="container grid max-w-[1280px] scroll-mt-28 gap-10 border-t border-border px-6 py-20 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Eyebrow>A little more clarity</Eyebrow><h2 className="mt-4 text-3xl font-medium leading-tight tracking-[-1px] sm:text-[40px]">Good questions.<br />Straight answers.</h2></Reveal><Accordion type="single" collapsible>{[{ q: 'Can ApexPrep help me work toward a 5?', a: 'That’s the goal. Practicing consistently, understanding mistakes, and reviewing key concepts can help you prepare. A 3-to-5 improvement is an ambition, not a promised outcome. The current demo does not provide validated AP score predictions.' }, { q: 'How close are the practice tests to the real AP exams?', a: 'Our goal is exam-relevant practice. This MVP currently uses a small pool of sample questions, with repeated questions in simulated tests. These are not official or validated full-length AP exams. Use official College Board resources alongside your prep.' }, { q: 'Can I try it for free?', a: 'Yes. You can answer the sample question right here or explore the free demo, including practice drills and one simulated test. No credit card is required. Authentication uses real email/password accounts or Google sign-in. Pro upgrades remain simulated, and no payment is collected.' }, { q: 'Which subjects can I practice?', a: 'The demo includes AP Psychology, AP Computer Science Principles, AP Physics, and Honors Precalculus. Honors Precalculus is a supporting course, not an AP exam. More subjects are planned.' }, { q: 'Will my progress be saved?', a: 'Yes. Your selected subjects and completed practice sessions are saved to your own account. Sign in with the same method to pick up where you left off, even after refreshing or switching devices. Pro upgrades are still a demo and reset when you sign out or refresh.' }].map(({ q, a }, i) => <AccordionItem key={q} value={`faq-${i}`} className="border-border"><AccordionTrigger className="gap-4 py-5 text-sm font-medium hover:no-underline hover:text-primary">{q}</AccordionTrigger><AccordionContent className="pr-7 text-sm leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></section>
        <section className="container max-w-[1280px] px-5 pb-20 sm:px-8"><Reveal className="relative overflow-hidden rounded-3xl bg-lavender px-6 py-16 text-center"><Sparkles aria-hidden="true" className="absolute left-[8%] top-12 hidden h-8 w-8 rotate-12 text-purple-400 sm:block" /><Target aria-hidden="true" className="absolute bottom-12 right-[8%] hidden h-12 w-12 -rotate-12 text-purple-300 sm:block" /><Eyebrow>Your next chapter</Eyebrow><h2 className="relative mt-4 text-3xl font-medium leading-tight tracking-[-1.5px] sm:text-5xl">You bring the ambition.<br />We’ll bring the practice.</h2><p className="mt-5 text-sm text-muted-foreground">One question today. A little more confidence tomorrow.</p><StartButton onClick={onGetStarted} className="mt-7" /><p className="mt-4 text-[11px] text-muted-foreground">No credit card. No pressure. Just progress.</p></Reveal></section>
      </main>
      <footer className="border-t border-border bg-card"><div className="container max-w-[1280px] px-6 py-12 sm:px-8"><div className="flex flex-wrap items-start justify-between gap-10"><div><Brand onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} /><p className="mt-4 text-xs text-muted-foreground">Big goals. Better practice.</p></div><div className="flex flex-wrap gap-14"><div><p className="text-xs font-semibold">Explore</p><div className="mt-4 space-y-3">{navItems.slice(0, 2).map(([label, id]) => <a key={id} href={id} onClick={e => goTo(e, id)} className="block text-xs text-muted-foreground hover:text-primary">{label}</a>)}<button onClick={onGetStarted} className="block text-xs text-muted-foreground hover:text-primary">Try the demo</button></div></div><div><p className="text-xs font-semibold">ApexPrep</p><div className="mt-4 space-y-3">{[...navItems.slice(2), ['FAQs', '#faq']].map(([label, id]) => <a key={id} href={id} onClick={e => goTo(e, id)} className="block text-xs text-muted-foreground hover:text-primary">{label}</a>)}</div></div></div></div><div className="mt-10 flex flex-wrap items-start justify-between gap-5 border-t border-border pt-6 text-[10px] leading-relaxed text-muted-foreground"><p>© {new Date().getFullYear()} ApexPrep. Keep aiming higher.</p><p className="max-w-lg sm:text-right">Independent practice platform. Not affiliated with or endorsed by the College Board.<br />AP® is a trademark of the College Board. Demo content and results are illustrative.</p></div></div></footer>
    </div>
  );
};

export default LandingPage;
